"""initial schema

Revision ID: d6eed65d6838
Revises: 
Create Date: 2026-09-12 12:10:56.518843
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = 'd6eed65d6838'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Model khai create_type=False, nên migration phải tự tạo/xoá enum type.
# Nếu không, downgrade để sót type lại và lần upgrade sau sẽ vỡ.
ENUM_TYPES = [
    postgresql.ENUM('user', 'admin', name='user_role', create_type=False),
    postgresql.ENUM('standard', 'vip', 'couple', 'sweetbox', name='seat_type', create_type=False),
    postgresql.ENUM('pending', 'confirmed', 'cancelled', 'expired', name='booking_status', create_type=False),
    postgresql.ENUM('vnpay', 'momo', 'zalopay', name='payment_method', create_type=False),
    postgresql.ENUM('pending', 'completed', 'failed', 'refunded', name='payment_status', create_type=False),
]

(
    user_role_enum,
    seat_type_enum,
    booking_status_enum,
    payment_method_enum,
    payment_status_enum,
) = ENUM_TYPES



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for enum_type in ENUM_TYPES:
        enum_type.create(op.get_bind(), checkfirst=True)

    op.create_table('cinemas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('district', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc',CURRENT_TIMESTAMP)"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cinemas_city', 'cinemas', ['city'], unique=False)
    op.create_index('idx_cinemas_is_active', 'cinemas', ['is_active'], unique=False)
    op.create_table('genres',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('movies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('original_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('poster_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('trailer_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('director', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('cast_members', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('age_rating', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.CheckConstraint('duration_minutes > 0 AND duration_minutes <= 500', name='ck_movies_duration_minutes_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_movies_is_active', 'movies', ['is_active'], unique=False)
    op.create_index('idx_movies_release_date', 'movies', ['release_date'], unique=False)
    op.create_index('idx_movies_title', 'movies', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('role', user_role_enum, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_table('movie_genres',
    sa.Column('movie_id', sa.UUID(), nullable=False),
    sa.Column('genre_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.create_index('idx_movie_genres_genre_id', 'movie_genres', ['genre_id'], unique=False)
    op.create_index('idx_movie_genres_movie_id', 'movie_genres', ['movie_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cinema_id', sa.UUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('room_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('seats_per_row', sa.Integer(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.CheckConstraint('seats_per_row > 0', name='ck_rooms_seats_per_row_positive'),
    sa.CheckConstraint('total_rows > 0', name='ck_rooms_total_rows_positive'),
    sa.CheckConstraint('total_seats > 0', name='ck_rooms_total_seats_positive'),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinemas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cinema_id', 'name', name='uq_rooms_cinema_id_name')
    )
    op.create_index('idx_rooms_cinema_id', 'rooms', ['cinema_id'], unique=False)
    op.create_index('idx_rooms_is_active', 'rooms', ['is_active'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('row_label', sa.CHAR(length=1), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('seat_type', seat_type_enum, nullable=False),
    sa.Column('price_multiplier', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc',CURRENT_TIMESTAMP)"), nullable=False),
    sa.CheckConstraint('seat_number > 0', name='ck_seats_seat_number_positive'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'row_label', 'seat_number', name='uq_seats_room_id_row_label_seat_number')
    )
    op.create_index('idx_seats_room_id', 'seats', ['room_id'], unique=False)
    op.create_index('idx_seats_seat_type', 'seats', ['seat_type'], unique=False)
    op.create_table('showtimes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('movie_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc',CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc',CURRENT_TIMESTAMP)"), nullable=False),
    sa.CheckConstraint('base_price > 0', name='ck_showtimes_base_price_positive'),
    sa.CheckConstraint('end_time > start_time', name='valid_time_range'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_showtimes_is_active', 'showtimes', ['is_active'], unique=False)
    op.create_index('idx_showtimes_movie_id', 'showtimes', ['movie_id'], unique=False)
    op.create_index('idx_showtimes_room_id', 'showtimes', ['room_id'], unique=False)
    op.create_index('idx_showtimes_room_time', 'showtimes', ['room_id', 'start_time', 'end_time'], unique=False)
    op.create_index('idx_showtimes_start_time', 'showtimes', ['start_time'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('showtime_id', sa.UUID(), nullable=False),
    sa.Column('booking_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', booking_status_enum, nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.CheckConstraint('total_amount >= 0', name='ck_bookings_total_amount_positive'),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtimes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_code')
    )
    op.create_index('idx_bookings_booking_code', 'bookings', ['booking_code'], unique=False)
    op.create_index('idx_bookings_expires_at', 'bookings', ['expires_at'], unique=False)
    op.create_index('idx_bookings_pending_expires', 'bookings', ['status', 'expires_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('idx_bookings_showtime_id', 'bookings', ['showtime_id'], unique=False)
    op.create_index('idx_bookings_status', 'bookings', ['status'], unique=False)
    op.create_index('idx_bookings_user_id', 'bookings', ['user_id'], unique=False)
    op.create_table('booking_seats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_booking_seats_price_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'seat_id', name='uq_booking_seats_booking_seat')
    )
    op.create_index('idx_booking_seats_booking_id', 'booking_seats', ['booking_id'], unique=False)
    op.create_index('idx_booking_seats_seat_id', 'booking_seats', ['seat_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('payment_method', payment_method_enum, nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', payment_status_enum, nullable=False),
    sa.Column('payment_url', sa.Text(), nullable=True),
    sa.Column('callback_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index('idx_payments_booking_id', 'payments', ['booking_id'], unique=False)
    op.create_index('idx_payments_payment_method', 'payments', ['payment_method'], unique=False)
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.create_index('idx_payments_transaction_id', 'payments', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payments_transaction_id', table_name='payments')
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_payment_method', table_name='payments')
    op.drop_index('idx_payments_booking_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('idx_booking_seats_seat_id', table_name='booking_seats')
    op.drop_index('idx_booking_seats_booking_id', table_name='booking_seats')
    op.drop_table('booking_seats')
    op.drop_index('idx_bookings_user_id', table_name='bookings')
    op.drop_index('idx_bookings_status', table_name='bookings')
    op.drop_index('idx_bookings_showtime_id', table_name='bookings')
    op.drop_index('idx_bookings_pending_expires', table_name='bookings', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('idx_bookings_expires_at', table_name='bookings')
    op.drop_index('idx_bookings_booking_code', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('idx_showtimes_start_time', table_name='showtimes')
    op.drop_index('idx_showtimes_room_time', table_name='showtimes')
    op.drop_index('idx_showtimes_room_id', table_name='showtimes')
    op.drop_index('idx_showtimes_movie_id', table_name='showtimes')
    op.drop_index('idx_showtimes_is_active', table_name='showtimes')
    op.drop_table('showtimes')
    op.drop_index('idx_seats_seat_type', table_name='seats')
    op.drop_index('idx_seats_room_id', table_name='seats')
    op.drop_table('seats')
    op.drop_index('idx_rooms_is_active', table_name='rooms')
    op.drop_index('idx_rooms_cinema_id', table_name='rooms')
    op.drop_table('rooms')
    op.drop_index('idx_movie_genres_movie_id', table_name='movie_genres')
    op.drop_index('idx_movie_genres_genre_id', table_name='movie_genres')
    op.drop_table('movie_genres')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_movies_title', table_name='movies')
    op.drop_index('idx_movies_release_date', table_name='movies')
    op.drop_index('idx_movies_is_active', table_name='movies')
    op.drop_table('movies')
    op.drop_table('genres')
    op.drop_index('idx_cinemas_is_active', table_name='cinemas')
    op.drop_index('idx_cinemas_city', table_name='cinemas')
    op.drop_table('cinemas')

    for enum_type in reversed(ENUM_TYPES):
        enum_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
