"""Bookings schemas package."""
from app.modules.bookings.schemas.domain import (
    BookingCreate,
    BookingUpdate,
    BookingSeatInput,
    BookingStatusUpdate,
    SeatStatus,
    SeatWithPrice,
    SeatAvailabilityInfo,
    BookingCalculation,
    BookingDTO,
    ShowtimeDetail,
    BookingWithDetails,
    BookingSearchCriteria,
    UserBookingHistory,
    ShowtimeBookingSummary,
)

from app.modules.bookings.schemas.api import (
    BookingCreateRequest,
    BookingCancelRequest,
    BookingConfirmRequest,
    BookingResponse,
    BookingDetailResponse,
    BookingListResponse,
    AdminBookingListResponse,
    BookingQueryParams,
    ShowtimeDetailForBooking,
    SeatAvailabilityResponse,
    CalculateBookingRequest,
    BookingCalculationResponse,
    UpdateBookingStatusRequest,
)

__all__ = [
    # Domain schemas
    "BookingCreate",
    "BookingUpdate",
    "BookingSeatInput",
    "BookingStatusUpdate",
    "SeatStatus",
    "SeatWithPrice",
    "SeatAvailabilityInfo",
    "BookingCalculation",
    "BookingDTO",
    "ShowtimeDetail",
    "BookingWithDetails",
    "BookingSearchCriteria",
    "UserBookingHistory",
    "ShowtimeBookingSummary",
    # API schemas
    "BookingCreateRequest",
    "BookingCancelRequest",
    "BookingConfirmRequest",
    "BookingResponse",
    "BookingDetailResponse",
    "BookingListResponse",
    "AdminBookingListResponse",
    "BookingQueryParams",
    "ShowtimeDetailForBooking",
    "SeatAvailabilityResponse",
    "CalculateBookingRequest",
    "BookingCalculationResponse",
    "UpdateBookingStatusRequest",
]
